# Generated by Django 2.0 on 2017-12-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0002_auto_20171217_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
