# Generated by Django 2.0 on 2017-12-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0003_auto_20171217_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='context',
            field=models.TextField(max_length=5000),
        ),
    ]
